name: Test
on: pull_request

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
        poetry-version: ["latest"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Run image
        uses: abatilo/actions-poetry@v3
      - name: Install deps
        run: poetry install
      - name: Run tests
        run: poetry run pytest